### PR TITLE
Replace Just the Docs with MkDocs

### PR DESCRIPTION
**Pull request by mwermelinger**
[MkDocs](https://www.mkdocs.org) has a large [catalogue of plugins](https://github.com/mkdocs/catalog), including for generating API docs and using Jupyter notebooks, so it may be a better bet for the future than [Just the Docs](https://just-the-docs.com), which doesn't seem to have any plugins and has a smaller community of developers.

Another advantage is that MkDocs doesn't require ruby, gems and Jekyll. It's all Python to generate static sites. Makes it easier for others to contribute.

I do prefer the font, buttons and admonitions (callouts) of Just the Docs, but we can style MkDocs later if we want. (I used the [material](https://squidfunk.github.io/mkdocs-material/) theme.)

I've converted our docs to MkDocs, just minor changes: blank lines before lists, indent by 4 always, change the syntax for call outs. I've added a dark theme and the current algoesup.py docstrings.

To see the resulting static pages, run `pip install -r requirements.txt` to pick up the new packages and then `mkdocs serve`. Let me know what you think.

### CODE REVIEW

**Review by densnow — APPROVED** [review]
Yes, I agree with most of your comments.

Having an easier way to generate the API documentation is really the big plus point here (although there are ways to do this with jeykll as well, albeit more convoluted). I was just wondering the other day if we could do something similar with `algoesup` as you did with `paddles` for generating docs, and this solves that problem.

As you say the styling is a bit more "utilitarian" than just the docs (JTD), but in this instance we must choose function over form. Styling can always be tweaked.

I would push back on your comment comparing mkdocs to JTD, considering JTD is only a theme for jekyll. A fairer comparison would be jekyll to mkdocs, and jekyll does have a rather large eco system of plugins and themes.

Being written in Python is a big plus point, as we normally like to get "under the hood" and tinker with a few things, I am sure this will be no exception :smile:

**Comment by densnow** [comment]
Found this [plugin for mkdocs](https://github.com/JakubAndrysek/mkdocs-open-in-new-tab) to open external links (and PDFs) in new tabs, which might be useful for our docs. We could either add it as dependency, or borrow some of the code (with attribution) and hardwire it into the project.

**Comment by mwermelinger** [comment]
The notebooks are now rendered as part of the docs, which is more environmentally friendly than rendering on demand on nbviewer or GH. You will have to re-run pip to pickup the two new mkdocs plugins.

I've experimented with integrating the TOC of each page within the navigation panel, to save space for smaller screens, but I think it can get a bit confusing. Reverted to separate nav and TOC panels. Made nav panel fixed (no collapsing headings). I also tried sections in the header, but then you always have to scroll to the top of the page to go to a different section. I think the current configuration is the easiest to go directly from any page to any other page.

Please do check things and, if everything's OK, do squash and merge. Thanks.

**Comment by densnow** [comment]
@mwermelinger The `.github/workflows/pages.yml` is still set up for `jekyll`. We can delete this right?

**Comment by densnow** [comment]
Anyway, I guess that can all be sorted when you deploy the site. The notebooks seem to render nicely and no problems anywhere else AFAIK. I will go ahead and with the squash and merge now.

**Pull request merged**
